#!/bin/bash

# Quick Deploy to Vercel Script
# This script helps you deploy the Vibe-Agents frontend to Vercel

set -e

echo "🚀 Vibe-Agents Vercel Deployment Helper"
echo "========================================"
echo ""

# Check if vercel CLI is installed
if ! command -v vercel &> /dev/null; then
    echo "❌ Vercel CLI not found. Installing..."
    npm install -g vercel
fi

# Check if we're in the right directory
if [ ! -f "client/package.json" ]; then
    echo "❌ Please run this script from the project root directory"
    exit 1
fi

echo "✅ Vercel CLI is installed"
echo ""

# Prompt for backend URL
echo "📝 Deployment Configuration"
echo "----------------------------"
echo ""
read -p "Enter your backend API URL (e.g., https://api.yourdomain.com): " BACKEND_URL

if [ -z "$BACKEND_URL" ]; then
    echo "⚠️  No backend URL provided. Using default (localhost:8000) - NOT recommended for production"
    BACKEND_URL="http://localhost:8000"
fi

echo ""
echo "Backend URL: $BACKEND_URL"
echo ""

# Create or update .env.local
echo "📄 Creating environment configuration..."
cat > client/.env.local << EOF
# Next.js Client Environment Variables
# Auto-generated by deploy-vercel.sh

# API Configuration
NEXT_PUBLIC_API_URL=$BACKEND_URL

# Feature Flags
NEXT_PUBLIC_ENABLE_ANALYTICS=true
NEXT_PUBLIC_ENABLE_ERROR_REPORTING=true
EOF

echo "✅ Environment file created at client/.env.local"
echo ""

# Navigate to client directory
cd client

echo "🔍 Checking for Vercel project..."
if [ ! -d ".vercel" ]; then
    echo "No Vercel project found. Initializing..."
    echo ""
    vercel link --yes || vercel init
fi

echo ""
echo "🚀 Deploying to Vercel..."
echo "=========================="
echo ""

# Deploy
vercel --prod

echo ""
echo "✅ Deployment complete!"
echo ""
echo "📋 Next Steps:"
echo "   1. Add environment variables in Vercel Dashboard:"
echo "      - Go to your project settings"
echo "      - Navigate to Environment Variables"
echo "      - Ensure NEXT_PUBLIC_API_URL is set to: $BACKEND_URL"
echo ""
echo "   2. Update backend CORS settings:"
echo "      - Add your Vercel domain to ALLOWED_ORIGINS"
echo "      - Format: http://localhost:3000,https://your-app.vercel.app"
echo ""
echo "   3. Test your deployment:"
echo "      - Visit your Vercel URL"
echo "      - Verify agent functionality"
echo "      - Check browser console for errors"
echo ""
echo "📖 For detailed instructions, see VERCEL_DEPLOYMENT.md"
echo ""
